apiVersion: v1
kind: Service
metadata:
  name: sre-backend-service
  labels:
    app: sre-backend
    component: backend
spec:
  selector:
    app: sre-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
